# Надо сделать для прода: везде ограничение по ресурсам, мониторинг и сеть, резервное копирование дб
# В проде убрать имена контейнеров
# docker exec postgresql psql -U judge0 -c "ALTER USER judge0 WITH PASSWORD 'judge0';"
version: '3.8'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: ${LOG_MAX_SIZE:-100M}
      max-file: ${LOG_MAX_FILE:-3}
      compress: "${LOG_COMPRESS:-true}"


services:
  postgresdb:
    image: postgres:17-alpine
    container_name: postgresql_judge0
    env_file: ./judge0.conf
    volumes:
      - postgres-data-judge0:/var/lib/postgresql/data/
    <<: *default-logging
    restart: unless-stopped
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.2.4
    container_name: redis
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: ./judge0.conf
    <<: *default-logging
    restart: unless-stopped
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  judge0_server:
    image: mrkushalsm/judge0:cgv2

    env_file: ./judge0.conf
    container_name: judge0_server
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358" # В проде надо будет закрыть порт 
    privileged: true   # нехорошо            <---------
    <<: *default-logging
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2358/about"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  
  judge0_worker:
    image: mrkushalsm/judge0:cgv2
    container_name: judge0_worker
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true   # нехорошо            <---------
    <<: *default-logging
    depends_on:
      redis:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
      judge0_server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "pgrep", "-f", "bin/rails"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s


  postgresdb_data:
    image: postgres:17-alpine
    container_name: mse1h2026-judge0-lti_postgresdb_data
    restart: unless-stopped
    <<: *default-logging
    env_file: 
      - .env
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  backend:
    image: mse1h2026-judge0-lti_backend-python-fastapi:v.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-python-fastapi
    restart: unless-stopped
    <<: *default-logging
    env_file: 
      - .env
    depends_on:
      postgresdb_data:
        condition: service_healthy
      judge0_worker:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - app-net
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1024M

  frontend:
    image: mse1h2026-judge0-lti_frontend-nginx-react:v.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-nginx-react
    restart: unless-stopped
    <<: *default-logging
    env_file: 
      - .env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - app-net


volumes:
  postgresdb-data:
    driver: local
  postgres-data-judge0:
    driver: local

networks:
  app-net:
    driver: bridge