export const serverToMonaco: Record<string, string> = {
    "Plain Text": "plaintext",
    "Executable": "plaintext",
    "Assembly (NASM 2.14.02)": "asm",
    "Bash (5.0.0)": "shell",
    "Basic (FBC 1.07.1)": "vb",
    "C (GCC 7.4.0)": "c",
    "C (GCC 8.3.0)": "c",
    "C (GCC 9.2.0)": "c",
    "C (Clang 7.0.1)": "c",
    "C# (Mono 6.6.0.161)": "csharp",
    "C++ (GCC 7.4.0)": "cpp",
    "C++ (GCC 8.3.0)": "cpp",
    "C++ (GCC 9.2.0)": "cpp",
    "C++ (Clang 7.0.1)": "cpp",
    "Common Lisp (SBCL 2.0.0)": "plaintext",
    "D (DMD 2.089.1)": "plaintext",
    "Elixir (1.9.4)": "elixir",
    "Erlang (OTP 22.2)": "plaintext",
    "Fortran (GFortran 9.2.0)": "plaintext",
    "Go (1.13.5)": "go",
    "Haskell (GHC 8.8.1)": "plaintext",
    "Java (OpenJDK 13.0.1)": "java",
    "JavaScript (Node.js 12.14.0)": "javascript",
    "Lua (5.3.5)": "lua",
    "OCaml (4.09.0)": "plaintext",
    "Octave (5.1.0)": "plaintext",
    "Pascal (FPC 3.0.4)": "pascal",
    "PHP (7.4.1)": "php",
    "Prolog (GNU Prolog 1.4.5)": "plaintext",
    "Python (2.7.17)": "python",
    "Python (3.8.1)": "python",
    "Ruby (2.7.0)": "ruby",
    "Rust (1.40.0)": "rust",
    "TypeScript (3.7.4)": "typescript",
    "COBOL (GnuCOBOL 2.2)": "plaintext",
    "Kotlin (1.3.70)": "kotlin",
    "Objective-C (Clang 7.0.1)": "objective-c",
    "R (4.0.0)": "r",
    "Scala (2.13.2)": "scala",
    "SQL (SQLite 3.27.2)": "sql",
    "Swift (5.2.3)": "swift",
    "Visual Basic.Net (vbnc 0.0.0.5943)": "vb",
    "Perl (5.28.1)": "plaintext",
    "Clojure (1.10.1)": "plaintext",
    "F# (.NET Core SDK 3.1.202)": "fsharp",
    "Groovy (3.0.3)": "plaintext",
    "Multi-file program": "plaintext",
};

export const mapServerLangToMonaco = (serverLang: string | undefined) => {
    if (!serverLang) return "plaintext";
    return serverToMonaco[serverLang] ?? "plaintext";
};